### ISSUE TITLE
The magic kingdom

### ISSUE THREAD

**Issue by valmorian1234** [kdechant/eamon#40]
I will go through  at some point and redo that adventure in a different order, but I found the daughter before I ever found the king, because I used power to get through the boulder. so when I found the king the quest both started, and completed  then it wouldn't let me save, and said error saving player data. I had to close and reopen the browser and it reverted to before I had entered the adventure it seems

**Comment by valmorian1234** [comment]
so I ended up finding out how the adventure was meant to be completed. and also that the football player was not supposed to be a follower? when I went in with power they just auto followed me. when I went in the second time they didn't 
 and the game did actually save this time

**Comment by kdechant** [comment]
Some NPCs, like the baseball player and the hermit in Beginner's Cave, have a random friendliness. If you play the same adventure more than once, you might have them follow you one time and not another time. The higher your character's charisma, the more likely they are to follow.

Also, the power spell has random effects. In some adventures, it can teleport you to a random room. In the case of the Magic Kingdom, I'll need to fix it so that it won't teleport you into the mine, because that causes the quest to get out of order.

**Comment by kdechant** [comment]
I fixed the Power spell so it won't teleport the player into the mine or onto the river.

For kicks, I tried rescuing the princess without meeting the king first (by cheating). When I subsequently met the king, I saw both the beginning and end of the quest at the same time, and was sent straight to the main hall, which is logical.
