### ISSUE TITLE
In the dark over Furioso

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#49]
I know that being in the dark is part of the challenge of the beginning of this adventure, but the hints say that I can cast the Power spell for a temporary fix.

My character's cast the spell till she's blue in the face and nothing happens.  Is this a bug or am I doing something wrong?

**Comment by eburggraaf** [comment]
Presumably you learn the power spell before the adventure?



On April 11, 2020 10:29:18 PM damienhurrell <notifications@github.com> wrote:

I know that being in the dark is part of the challenge of the beginning of 
this adventure, but the hints say that I can cast the Power spell for a 
temporary fix.

My character's cast the spell till she's blue in the face and nothing 
happens.  Is this a bug or am I doing something wrong?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/kdechant/eamon/issues/49

**Comment by damienhurrell** [comment]
Oh yes, this character knows the spell.  And casts it successfully in other adventures.

I've played this adventure multiple times and cast the spell multiple times per visit.  I don't think I'm just unlucky.

Here's the transcript:

You wake up on a hard wooden floor, somewhere dark and stuffy. You seem to have sustained a few bruises. In the distance, you can hear shouting and ocean sounds.

You have been stripped of all your weapons and armor. And speaking of stripped.....They took all your clothes too!

You hear a man's voice in the darkness. He says, 'Good, you're awake. I'm Orlando. I was kidnapped by the smugglers, too. We need to get out of here, pronto.'

The floor is covered with water which seems to be slowly rising...

It's too dark to see anything.

POWER
The floor is covered with water which seems to be slowly rising...

It's too dark to see anything.

POWER
Nothing happens.

The floor is covered with water which seems to be slowly rising...

It's too dark to see anything.

POWER
Nothing happens.

The floor is covered with water which seems to be slowly rising...

It's too dark to see anything.

**Comment by kdechant** [comment]
The POWER spell in that adventure summons an artifact that's a light source. The issue is that the light source is unlit by default, and since it's dark in the room, you don't even know it's there. The first time you cast POWER in your transcript above was when the artifact appeared, and if you typed GET ALL you could have picked it up. But what's supposed to happen is that you see the artifact description and the lights come on immediately.

I have a fix coming out soon.

**Comment by damienhurrell** [comment]
Thanks

**Comment by damienhurrell** [comment]
Woohoo! tested and working:

You wake up on a hard wooden floor, somewhere dark and stuffy. You seem to have sustained a few bruises. In the distance, you can hear shouting and ocean sounds.

You have been stripped of all your weapons and armor. And speaking of stripped.....They took all your clothes too!

You hear a man's voice in the darkness. He says, 'Good, you're awake. I'm Orlando. I was kidnapped by the smugglers, too. We need to get out of here, pronto.'

The floor is covered with water which seems to be slowly rising...

It's too dark to see anything.

POWER
Spell ability increased!

There is a sudden bright flash and a glowing ball appears in the room. You can use it to see, and it has a convenient on/off switch.

You are in the brig. (N)

You are in a room made of very rough wood. It seems to be fitted out as a detention area of some kind, with chains and manacles attached to the walls. There is an unlocked door in the north wall.

You see a blond, heavily tanned man. He has a long scar on his left cheek, giving him a sort of lopsided sneer.

You see warm salt water covering the floor. The water is rising slowly.

You see glowing ball.
