### ISSUE TITLE
Treasure Island / Flute Doors

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#6]
1. 1. Not really a bug in the program per se, but when I play the flute on one side of the door it unlocks. Great. I go through. But it's locked on the other side of the door and I have to play the flute again. I understand why it was set up this way, but logic would suggest that the door should be unlocked on both sides.

2. Silver Chest should be treated as a container object. I can't open it. When I tried to "put potion in chest" I get the response "I can't put things into the chest!"

3. Can't seem to remove doubloons from other chest (dragon's). Can't pick up that chest either. 

4. Magic dagger is a "spear"

**Comment by kdechant** [comment]
1. The flute behavior was like that in the original and in Eamon Deluxe IIRC. I just re-implemented the same logic.
2. In EDX, Frank treated the silver chest as a treasure and not a container. It stayed that way when I imported the data. I might consider changing it because it's kind of weird. (I can't check the Apple II original, because it was written in Main Program v4 which didn't have the concept of a container artifact.)
3. There is a name conflict that prevents you from targeting the "chest" if you're carrying the "silver chest" (due to the fuzzy matching). It was like this in EDX as well and I haven't found a perfect solution yet. As a workaround, try dropping the silver chest in a different room, then come back and interact with the dragon's chest.
4. Frank also reclassified lots of dagger and short sword type weapons as "spears" due to the stabbing motion you use when fighting with them. (It's actually explained that way in the EDX adventure design manual.) So they all came over as spears when I imported the data. I might go through and change them back to swords, because I thought the original meaning of the "spear" category was "pole-arm", not "short stabbing weapon".

**Comment by EamonAG** [comment]
Fair enough on all of these. I guess my thought is that while Frank made certain decisions for Eamon Deluxe, if there are more logical decisions, that would be ideal. You may not think of it but for a play through though...

**Comment by kdechant** [comment]
I have recategorized a bunch of dagger and knife weapons as swords, which is how most of them were in the Apple version. I'm working on fixing a few of the other data-related oddities as well.

**Comment by kdechant** [comment]
I have added a feature called "linked doors" which is useful when two sides of the same door appear as separate artifacts in two different rooms. This feature will open both "sides" of the door when either side is opened, and will close both sides when either side is closed.
