### ISSUE TITLE
Lost everything!

### ISSUE THREAD

**Issue by damienhurrell** [kdechant/eamon#61]
I failed to secure the Sword of Inari and was punished with the loss of everything!

It's a fair cop, but I didn't have any money in the bank so I can't get a weapon, and so the Irishman won't let me go out to rebuild my fortune.

I've invested a lot of time in this character.  Is there something I can do to get him going again, or is he condemned to penury and impotence?

**Comment by kdechant** [comment]
The Irishman's warning is just supposed to be a reminder and is not supposed to actually stop you from going on adventures. But I just tried to start an adventure with a character with no items and got an error that prevents the adventure from starting. I'll have to fix that up tonight.

**Comment by damienhurrell** [comment]
Ha!  I'm obviously enough of a lawful alignment that I just docilely went back to the Hall.

**Comment by kdechant** [comment]
The error is fixed.

Might be a good time to go through Furioso, because you lose all your gear at the start of that adventure anyway.

**Comment by damienhurrell** [comment]
Good point.

**Comment by eburggraaf** [comment]
Do you have blast?  Iif so, you may be able to mount an epic comeback.  
There's a designer sword laying around in the Alice in wonderland adventure.




On April 29, 2020 7:28:58 PM damienhurrell <notifications@github.com> wrote:

I failed to secure the Sword of Inari and was punished with the loss of 
everything!

It's a fair cop, but I didn't have any money in the bank so I can't get a 
weapon, and so the Irishman won't let me go out to rebuild my fortune.

I've invested a lot of time in this character.  Is there something I can do 
to get him going again, or is he condemned to penury and impotence?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/kdechant/eamon/issues/61

**Comment by damienhurrell** [comment]
I'm back baby!
