### ISSUE TITLE
Prince's Tavern

### ISSUE THREAD

**Issue by EamonAG** [kdechant/eamon#8]
Gold key doesn't appear when you kill the prince.
-------------------
I had fled a battle and the ogre was in the Gerschter bar with me. I tried to attack ogre and got this message. 

"Several quick-acting men whisk you out of the establishment, dump you on a hard floor (bruising your knee) and advise you to be a little more courteous next time you're out in public.

Error: Cannot read property 'id' of null"

Doesn't look like I was in a room and it appeared to crash the program (it wouldn't take any more inputs).
---------------------------------
If you drop your shield and then pick it up and try to wear it, you get this response:
wear shield
Error: Cannot read property 'hands' of null
---------------------
If you are in the drinking contest and your agility drops, it's supposed to go back up. Well, if you drink the brew and your agility goes negative, it doesn't reset when you leave. Thus, I am now the proud owner of a -5 agility character!

**Comment by kdechant** [comment]
The gold key thing was like that in the Apple II version, due to the older main program which didn't allow NPCs to have an inventory. I added the key to the Prince's inventory so he'll drop it when he dies.

As you guessed, the Gerschter bar logic was causing the player to end up in a null room. This is fixed.

The shield error happened if you tried to equip a shield without having a weapon ready. This is also fixed.

The "sobering up" logic at the exit was broken and would only work in one very specific case. I fixed it so it now works at every exit, including the two hidden ones. I also added a time-based routine for slowly sobering the player up if they wander around for a while without drinking anything. This is useful because the fire worm kept killing me due to my low agility after the drinking contest. (This wasn't a problem in the Apple II version, which used MAIN PGM v4 combat logic, which put less importance on agility.)
